export const coffeeFacts = [
    "Coffee is actually a fruit. The beans are the pits of cherries.",
    "Beethoven was obsessive about his coffee, using exactly 60 beans per cup.",
    "Espresso means 'pressed out' in Italian.",
    "Finland consumes the most coffee per capita in the world.",
    "Decaf coffee is not 100% caffeine-free.",
    "Coffee was originally chewed by African tribes for energy.",
    "A 'Short Black' is an Australian term for an espresso shot.",
    "The word 'coffee' comes from the Arabic word for 'wine'.",
    "Brazil is the largest coffee producer in the world, responsible for about a third of the supply.",
    "There are two main types of coffee beans: Arabica and Robusta.",
    "Coffee is the second most traded commodity in the world, surpassed only by crude oil.",
    "The first webcam was invented at the University of Cambridge to check if the coffee pot was full.",
    "Teddy Roosevelt reportedly drank a gallon of coffee a day.",
    "Kopi Luwak is the most expensive coffee in the world and comes from beans digested by civet cats.",
    "Coffee can stay warm 20% longer when you add cream.",
    "Before coffee became popular, beer was the breakfast drink of choice in many places.",
    "In 17th-century England, women were banned from coffee houses.",
    "The average American spends over $1,000 on coffee annually.",
    "Instant coffee has been around for nearly 250 years.",
    "Adding milk to your coffee weakens the effects of caffeine.",
    "Dark roast coffees actually have slightly less caffeine than light roasts.",
    "Scientists are working on using coffee grounds as a source of biodiesel.",
    "The Boston Tea Party helped make drinking coffee a patriotic duty in America.",
    "Starbucks opens an average of two stores every day.",
    "Coffee beans are technically seeds.",
    "Drinking coffee may lower the risk of Type 2 diabetes.",
    "Bach wrote an entire cantata dedicated to his love of coffee.",
    "Japan celebrates an official Coffee Day on October 1st.",
    "In Turkey, coffee grounds are often used to tell fortunes.",
    "The lethal dose of caffeine is roughly 100 cups of coffee.",
    "Coffee plants can live for up to 100 years.",
    "Hawaiian coffee is the only commercially grown coffee in the United States.",
    "An 'Americano' comes from WWII soldiers watering down their espresso to mimic drip coffee.",
    "In ancient Arab culture, a woman could legally divorce her husband if he didn't provide enough coffee.",
    "Coffee was banned in Mecca in 1511 because leaders believed it stimulated radical thinking.",
    "40% of the world’s coffee is produced by just two countries: Brazil and Vietnam.",
    "Cappuccino is named after the Capuchin friars because the color resembles their robes.",
    "Drinking coffee before a workout can improve physical performance by 11-12%.",
    "Voltaire supposedly drank up to 50 cups of coffee a day.",
    "Coffee grounds are great for your garden because they are rich in nitrogen.",
    "It takes about 42 coffee beans to make a single shot of espresso.",
    "The largest cup of coffee ever made was over 6,000 gallons.",
    "Instant coffee was invented by a man named George Washington (not the president).",
    "Simply smelling coffee can alter the activity of genes in the brain to reduce stress.",
    "A coffee tree yields less than one to two pounds of coffee beans per year.",
    "Legend says a goat herder named Kaldi discovered coffee when his goats became energetic after eating the berries.",
    "In 1675, King Charles II banned coffee shops in England because he thought people were plotting against him there.",
    "The world's first webcam was created at Cambridge University specifically to watch a coffee pot.",
    "Light roast coffee has more caffeine than dark roast because the roasting process burns off some caffeine.",
    "Coffee is the most popular beverage in the world, with over 400 billion cups consumed each year.",
    "Before people learned how to brew coffee, East African tribes mixed coffee berries with animal fat to make energy balls.",
    "Ideally, coffee should be consumed at 140°F (60°C) for the best flavor profile.",
    "There is a spa in Japan where you can bathe in coffee, tea, or wine.",
    "Coffee beans are actually green before they are roasted.",
    "The Dutch were the first Europeans to trade coffee on a commercial basis.",
    "New Yorkers drink 7 times more coffee than the rest of the US.",
    "One cup of black coffee only has one calorie.",
    "The CIA headquarters has a Starbucks, but the baristas are not allowed to write names on the cups for security reasons.",
    "It takes about 3 to 4 years for a coffee tree to mature and produce its first crop.",
    "The majority of coffee is produced in the 'Bean Belt,' the area between the Tropics of Cancer and Capricorn.",
    "Robusta beans have double the caffeine of Arabica beans, but are generally considered lower quality.",
    "The name 'Cappuccino' comes from the resemblance of the drink to the clothing of the Capuchin monks.",
    "If you yelled for 8 years, 7 months, and 6 days, you would produce enough sound energy to heat one cup of coffee.",
    "Globally, people consume about 2.25 billion cups of coffee every day.",
    "The largest cup of coffee ever filled was 20,000 liters (over 5,000 gallons) in South Korea in 2014.",
    "Coffee grounds can be used as a natural exfoliator for skin.",
    "In Italy, espresso is regulated by the government because it is considered an essential part of daily life.",
    "During the Civil War, soldiers who couldn't get coffee used roasted sweet potato and Indian corn as a substitute.",
    "Postum, a caffeine-free coffee substitute made from roasted wheat and molasses, was popular during WWII rationing.",
    "The most expensive coffee in the world, Black Ivory Coffee, is naturally refined by elephants.",
    "Regular coffee drinkers have a lower risk of developing Alzheimer's disease and dementia.",
    "In France, dipping a croissant in your coffee is a socially acceptable breakfast ritual.",
    "An espresso shot contains about 63mg of caffeine, while a standard cup of drip coffee has about 95mg.",
    "Some studies suggest that coffee can help prevent cavities because it kills bacteria that cause tooth decay (if drunk black).",
    "Instant coffee accounts for nearly 50% of all coffee consumption in some countries, like the UK.",
    "The average coffee tree produces about 10 pounds of coffee cherries per year, which yields just 2 pounds of green beans.",
    "Blue Mountain Coffee from Jamaica is one of the most sought-after and expensive coffees in the world.",
    "Drinking coffee can boost your metabolic rate by 3-11%.",
    "Cold brew coffee is less acidic than hot brewed coffee, making it easier on the stomach.",
    "The term 'Cup of Joe' is believed to refer to Josephus Daniels, who banned alcohol on Navy ships, leaving coffee as the strongest drink.",
    "In the 18th century, Germany tried to ban coffee because they wanted people to drink more beer to support local breweries.",
    "Coffee was declared a Christian drink by Pope Clement VIII in 1600 after he tried it and loved it.",
    "Starbucks uses over 4 billion paper cups annually.",
    "A 'Red Eye' is a cup of drip coffee with one shot of espresso added to it.",
    "A 'Black Eye' is a cup of drip coffee with two shots of espresso.",
    "A 'Dead Eye' (or Green Eye) is a cup of drip coffee with three shots of espresso.",
    "The first coffee house in Europe opened in Venice in 1647.",
    "Coffee was once used as grounds for divorce in ancient Constantinople if a husband failed to provide his wife with fresh coffee.",
    "The steam wand on an espresso machine was invented in 1901 by Luigi Bezzera.",
    "Aeropress championships exist worldwide, where competitors use the same beans to brew the best cup.",
    "Coffee has over 1,000 chemical compounds that contribute to its flavor and aroma.",
    "Before the 10th century, coffee was considered a food, not a beverage.",
    "The 'crema' on top of an espresso acts as a cap that traps the coffee's aroma.",
    "Over 50% of Americans over the age of 18 drink coffee every day.",
    "Scandinavian countries dominate the top 5 list of coffee consumers per capita.",
    "There is a 'Coffee Cantata' written by Johann Sebastian Bach, which is essentially a mini-opera about coffee addiction."
];